version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: aiagent_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aiagent
      POSTGRES_PASSWORD: aiagentpassword
      POSTGRES_DB: aiagent_studio
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aiagent"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data: